spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:11.4://hostname/databasename?TC_INITSCRIPT=file:src/integTest/resources/init-main-schema.sql&TC_DAEMON=true&TC_TMPFS=/var/lib/postgresql/data:rw
  session:
    store-type: none