version: "3.7"
services:
  postgres:
    ports:
      - "5432:5432"
    image: postgres:12.6
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./volume/postgres:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: "nc-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  nc-app:
    build: ../docker-image/
    image: nc-app:latest
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      DB_ADDR: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      SESSION_DB: session-db
      SESSION_DB_USER: postgres
      SESSION_DB_PASSWORD: postgres

volumes:
  pg-data: