spring:
  application:
    name: nc-app
  datasource:
    url: jdbc:postgresql://${DB_ADDR:localhost}:5432/nc-db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
    database:
      url: jdbc:postgresql://${DB_ADDR:localhost}:5432/${SESSION_DB:session-db}
      username: ${SESSION_DB_USER:postgres}
      password: ${SESSION_DB_PASSWORD:postgres}
      driverClassName: org.postgresql.Driver

server:
  port: 8081
logging:
  level:
    org.springframework.*: debug
