spring:
  application:
    name: nc-app
  datasource:
    url: jdbc:postgresql://${DB_ADDR:localhost}:5432/nc-db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
server:
  port: 8080